### ISSUE TITLE
Meta-issue: Async related issues

### ISSUE THREAD

**Issue by crusso** [caffeinelabs/motoko#2232]
- [ ] Prelude scheduling not async enough (#691)
- [ ] Oneway scheduling (#1162)
- [ ] Locally abstracting over async calls (#680)
- [ ] Optimize async translation (#975, #1039, #1353)
- [ ] Support abstraction of async code (#1482)
