### ISSUE TITLE
Meta-issue: Type system gaps

### ISSUE THREAD

**Issue by rossberg** [caffeinelabs/motoko#2301]
Small:
- [x] Do not infer None when not principal (#1639)
- [x] Warn about unused identifiers (#1489)

Medium:
- [x] Complete lub/glb (#2330, #515)
- [x] Detect non-uniform type recursion (#1280)
- [x] Detect non-contractive type recursion (#1279)
- [x] Closing types over type variables (#491?)
- [x] Support type components in object types (#760)
- [x] Remove avoidance (#2405) 
- [ ] Possible looping with type comparison (#2460)

Large:
- [x] Check interfaces on upgrades (#1429)
- [x] Check stable interface on upgrades (#1430, #1431)
- [ ] Formal language spec (#1436)
