### ISSUE TITLE
Meta-issue: Performance improvements

### ISSUE THREAD

**Issue by rossberg** [caffeinelabs/motoko#2302]
Small:
- [ ] Short-cut structural equality based on pointer equality (#1838)
- [ ] Field access (#915)
- [x] BigInt representation (#2250)

Medium:
- [ ] For-loops (#973)
- [ ] Share immutable stable values (#1497)
- [ ] Non-uniform array representation? (#966)
- [ ] Variant representation? (#916)
- [ ] Async translation (#975)
- [ ] Try/catch (#976)

Large:
- [ ] Mid-call GC (#2033)
- [ ] Page GC (#1670)
