### ISSUE TITLE
Meta-issue: Tooling

### ISSUE THREAD

**Issue by rossberg** [caffeinelabs/motoko#2308]
Small:

Medium:
- [x] Generate xref links in mo-doc
- [ ] Improve type pretty-printing (#2269)
- [x] Canister parameters (#1827)
- [x] Show documentation in completions (#2349)
- [ ] Cross-reference other packages (#2350)
- [ ] Documentation for Prim types (#2351)
- [ ] Allow users to write Xrefs in their doc strings (#2352)
- [ ] Include source code in generated documentation (#2353)

Large:
- [x] Check interfaces on upgrades (#1429)
- [x] Check stable interface on upgrades (#1430, #1431)
- [x] White-space preserving parser (#2224)
- [x] Code formatter
- [x] Unit testing framework (#1860)
- [ ] ~C library for Candid~
- [ ] ~IC emulator~
- [x] FFI (#1400)
